# Generated by Django 6.0.3 on 2026-03-15 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servicio', models.CharField(choices=[('ENFERMERIA', 'Enfermería'), ('NUTRICION', 'Nutrición'), ('ODONTOLOGIA', 'Odontología'), ('PSICOLOGIA', 'Psicología'), ('MEDICINA', 'Medicina')], max_length=20)),
                ('orden', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesional_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='core.visita')),
            ],
            options={
                'verbose_name': 'Derivación',
                'verbose_name_plural': 'Derivaciones',
                'ordering': ['visita', 'orden'],
                'unique_together': {('visita', 'servicio')},
            },
        ),
    ]
