# Generated by Django 6.0.3 on 2026-03-16 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='token_acceso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
